book/urls.py
from django.urls import path
from . import views

app_name="book"
urlpatterns = [
    #http://localhost:8000/book
    path('',views.index,name="index"),
    path('create/',views.create,name="create"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete")
]

bookingsystem/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home.urls')),
    path('book/',include('book.urls')),
    path('restaurant/',include('restaurant.urls')),
    path('member/',include('member.urls'))
]

restaurant/urls.py
from django.urls import path
from . import views

app_name="restaurants"
urlpatterns = [
    #http://localhost:8000/product
    path('',views.index,name="index"),
    #http://localhost:8000/product/create
    path('create/',views.create,name="create"),
    #http://localhost:8000/product/update
    path('update/<int:id>',views.update,name="update"),
    #http://localhost:8000/product/delete/1
    path('delete/<int:id>',views.delete,name="delete")
]

restaurant/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    rname = models.TextField()
    rtype = models.TextField()
    rtel= models.TextField()
    raddress = models.DateField()
    rweb= models.TextField()
    rintroduction= models.TextField(max_length=500)
    
    class Meta:
        db_table = "restaurants"

restaurant/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from . import modelsrestaurants
# from . import modelsproduct
from .modelsrestaurant import restaurant

# Create your views here.
def index(request):
    title="餐廳管理"
    # product = modelsproduct.Product()
    res = restaurant()
    datas = res.all()
    return render(request,'R20/index.html',locals())

def create(request):
    title="餐廳新增"
    # print(request.method);
    #POST
    if request.method == "POST":
        #取得表單透過POST傳過來的資料
        rtype = request.POST['rtype']
        rname = request.POST['rname']
        rtel = request.POST['rtel']
        raddress = request.POST['raddress']
        rweb = request.POST['rweb']
        rintroduction = request.POST['rintroduction']

        #todo 把資料寫進資料庫
        res = restaurant() 
        data = tuple([rname,rtype,rtel,raddress,rweb,rintroduction])
        res.create(data)
       
        return redirect('/restaurant/')
        
    #GET
    #回傳一個網頁，讓使用者可以輸入資料
    category = modelsrestaurants.restaurants()
    datas = category.all()
    # print(datas)  #((),(),())
    return render(request,'R20/create.html',locals())
def beforeupdate(request):
    title="餐廳管理"
    # product = modelsproduct.Product()
    res = restaurant()
    datas = res.all()
    return render(request,'R20/beforeupdate.html',locals())

def update(request, id):
    #步驟二
    if request.method == "POST":
        # #上傳檔案
        # myFile = request.FILES["ProductImage"]
        # fs = FileSystemStorage()
        # fs.save(myFile.name, myFile)
        
        #取得表單透過POST傳過來的資料
        rtype = request.POST['rtype']
        rname = request.POST['rname']
        raddress = request.POST['raddress']
        rweb = request.POST['rweb']
        rtel = request.POST['rtel']
        rintroduction = request.POST['rintroduction']
        # ProductImage = myFile.name
        restaurantsid = request.POST['restaurantsid']

        res = restaurant() #modelsproduct.Product()
        data = tuple([rname,rtype,rtel,raddress,rweb,rintroduction,restaurantsid])
        res.update(data)
        return redirect('/restaurant/')

    title="餐廳修改"
    #步驟一
    res = restaurant()
    data = res.single(id)
    category = modelsrestaurants.restaurants()
    datas = category.all()
    return render(request,'R20/update.html',locals())

def delete(request, id):
    # print(id)
    res = restaurant() #modelsproduct.Product()
    res.delete(id)
    return redirect('/restaurant/')

restaurant/templates/R20/beforeupdate.html
{% extends "base.html" %} {% block body %}
{% if request.COOKIES.name == "user" %}
<div style="position: fixed; ">
    <a href="{% url 'restaurants:create' %}" class="btn btn-primary" style="margin : 5px auto">
        <i class="fas fa-plus-square"></i>餐廳新增</a>
    <a class="btn btn-primary" href="{% url 'restaurants:index' %}">
        <i class="fas fa-cog"></i>餐廳設定</a>
</div>
{% endif %}
<div style="width: 50%;margin: 15px auto">
    <dl style="padding: 5px;font-size: 24px">
        {% for res in datas %}
        <h2 class="alert alert-primary" style="border-radius: 20px 20px 0 0">
            <i class="fab fa-python"></i>餐廳名稱:{{res.1}}
            <a style="margin:5px 5px;float:right" href="{% url 'restaurants:delete' res.0  %}" class="btn btn-danger">
                <i class="fas fa-trash-alt"></i>
            </a>
            <a style="margin:5px 5px;float:right;" href="{% url 'restaurants:update' res.0  %}" class="btn btn-danger">
                <i class="fas fa-pencil-alt"></i>
            </a>
        </h2>
        <p>
            <i class="fas fa-boxes"></i>餐廳類型:{{res.2}}</p>
        <p>
            <i class="fas fa-phone"></i>餐廳電話:{{res.3}}</p>
        <p>
            <i class="fas fa-map-marker"></i>餐廳地址:{{res.4}}</p>
        <p>
            <i class="fas fa-link"></i>餐廳網址:
            <a href="{{res.5}}">{{res.5}}</a>
        </p>
        <p>
            <i class="fas fa-comment"></i>餐廳評論:{{res.6}}</p>
        {% endfor %}
    </dl>
</div>
{% endblock %}

restaurant/templates/R20/create.html
{% extends "base.html" %}
{% block body %}
<h2 style="text-align:center;font-weight:bold;">餐廳新增</h2>
<hr />
<form method="POST" enctype="multipart/form-data" style="margin:10px auto;background-color: whitesmoke;width: 50%;border-radius: 15px 15px 0 0">
    {% csrf_token %}
    <div class="form-group row" style="padding:15px">
            <label for="rtype" class="col-sm-2 col-form-label col-form-label-lg">餐廳類型</label>
            <div class="col-sm-10">
              <select style="width: 100%" class="form-control form-control-lg" name="rtype" id="rtype">
                 <option value="0">請選擇</option>
                 <option value="中式">中式</option>
                 <option value="西式">西式</option>
                 <option value="日式">日式</option>
                 <option value="台式">台式</option>
                 <option value="法式">法式</option>
                 <option value="港式">港式</option>
                 <option value="其他">其他</option>
              </select> 
            </div>
          </div>
  <div class="form-group row" style="padding:15px">
    <label for="rname" class="col-sm-2 col-form-label col-form-label-lg">餐廳名稱</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="text" class="form-control form-control-lg" name="rname" id="rname" placeholder="請輸入餐廳名稱">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
      <label for="rtel" class="col-sm-2 col-form-label col-form-label-lg">餐廳電話</label>
      <div class="col-sm-10">
        <input style="width: 100%" type="tel" class="form-control form-control-lg" name="rtel" id="rtel" placeholder="請輸入餐廳電話">
      </div>
    </div>
  <div class="form-group row" style="padding:15px">
    <label for="raddress" class="col-sm-2 col-form-label col-form-label-lg">餐廳地址</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="text" class="form-control form-control-lg" name="raddress" id="rassress" placeholder="請輸入餐廳地址">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rweb" class="col-sm-2 col-form-label col-form-label-lg">餐廳網址</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="url" class="form-control form-control-lg" name="rweb" id="rweb" value="https://">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rintroduction" class="col-sm-2 col-form-label col-form-label-lg">餐廳簡介</label>
    <div class="col-sm-10">
      <textarea style="width: 100%" class="form-control form-control-lg" name="rintroduction" id="rintroduction"></textarea>
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> 新增</button>
    </div>
  </div>
</form>
{% endblock %}

restaurant/templates/R20/index.html
{% extends "base.html" %} {% block body %}
{% if request.COOKIES.name == 'user' %}
<div style="position: fixed; ">
    <a href="{% url 'restaurants:create' %}" class="btn btn-primary" style="margin : 5px auto">
        <i class="fas fa-plus-square"></i>餐廳新增</a>
    

</div>
{% endif %}

<div style="width: 50%;margin: 15px auto">
    <dl style="padding: 5px;font-size: 24px;background-color: white;border-radius: 20px 20px 0 0">
        {% for res in datas %}

        <h2 class="alert alert-primary" style="border-radius: 20px 20px 0 0"><i class="fab fa-python"></i>餐廳名稱:{{res.1}}</h2>
        <p><i class="fas fa-boxes"></i>餐廳類型:{{res.2}}</p>
        <p><i class="fas fa-phone"></i>餐廳電話:{{res.3}}</p>
        <p><i class="fas fa-map-marker"></i>餐廳地址:{{res.4}}</p>
        <p><i class="fas fa-link"></i>餐廳網址: <a href="{{res.5}}">{{res.5}}</a></p>
        <p><i class="fas fa-comment"></i>餐廳評論:{{res.6}}</p>
        {% if request.COOKIES.name == 'user' %}
        <a class="btn btn-primary" href="{% url 'restaurants:update' res.0 %}">
            <i class="fas fa-cog">餐廳設定</i></a>
        <a class="btn btn-primary" href="{% url 'restaurants:delete' res.0 %}">
            <i class="fas fa-cog">餐廳刪除</i></a>
        {% endif %}
        {% endfor %}

    </dl>
</div>
{% endblock %} 

restaurant/templates/R20/update.html
{% extends 'base.html' %} {% block body %}
<h2 style="text-align:center;font-weight:bold;">餐廳修改</h2>
<hr />
<form method="POST" enctype="multipart/form-data" style="margin:10px auto;background-color: whitesmoke;width: 50%;border-radius: 15px 15px 0 0">
  {% csrf_token %}
  <div class="form-group row" style="padding:15px">
    <label for="rtype" class="col-sm-2 col-form-label col-form-label-lg">餐廳類型</label>
    <div class="col-sm-10">
      <select style="width: 100%" class="form-control form-control-lg" name="rtype" id="rtype">
        <option value="0">請選擇</option>
        <option value="中式">中式</option>
        <option value="西式">西式</option>
        <option value="日式">日式</option>
        <option value="台式">台式</option>
        <option value="法式">法式</option>
        <option value="港式">港式</option>
        <option value="其他">其他</option>
      </select>
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rname" class="col-sm-2 col-form-label col-form-label-lg">餐廳名稱</label>
    <div class="col-sm-10">
      <input type="hidden" name="restaurantsid" value="{{data.0}}" />
      <input style="width: 100%" type="text" value="{{data.1}}" class="form-control form-control-lg" name="rname" id="rname" placeholder="請輸入餐廳名稱">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rtel" class="col-sm-2 col-form-label col-form-label-lg">餐廳電話</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="text" value="{{data.3}}" class="form-control form-control-lg" name="rtel" id="rtel" placeholder="請輸入餐廳電話">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="raddress" class="col-sm-2 col-form-label col-form-label-lg">餐廳地址</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="text" value="{{data.4}}" class="form-control form-control-lg" name="raddress" id="raddress" placeholder="請輸入餐廳地址">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rweb" class="col-sm-2 col-form-label col-form-label-lg">餐廳網址</label>
    <div class="col-sm-10">
      <input style="width: 100%" type="url" value="{{data.5}}" class="form-control form-control-lg" name="rweb" id="rweb">
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <label for="rintroduction" class="col-sm-2 col-form-label col-form-label-lg">餐廳簡介</label>
    <div class="col-sm-10">
      <textarea style="width: 100%" class="form-control form-control-lg" name="rintroduction" id="rintroduction">{{data.6}}</textarea>
    </div>
  </div>
  <div class="form-group row" style="padding:15px">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">
        <i class="fas fa-plus-circle"></i> 修改</button>
    </div>
  </div>
</form>
{% endblock %}