book/urls.py
from django.urls import path
from . import views

app_name="book"
urlpatterns = [
    #http://localhost:8000/book
    path('',views.index,name="index"),
    path('create/',views.create,name="create"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete")
]

bookingsystem/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home.urls')),
    path('book/',include('book.urls')),
    path('restaurant/',include('restaurant.urls')),
    path('member/',include('member.urls'))
]

book/models.py
from django.db import models

# Create your models here.
class Booking(models.Model):
    
    restaurantname = models.TextField()
    bookname = models.TextField()
    bookperson = models.PositiveIntegerField()
    booktel= models.TextField()
    bookdate= models.TextField()
    bookwhen = models.TextField()
    booktime = models.TextField()
    
    class Meta:
        db_table = "book"
class Restaurant(models.Model):
    rname = models.TextField()
    rtype = models.TextField()
    rtel= models.TextField()
    raddress = models.DateField()
    rweb= models.TextField()
    rintroduction= models.TextField(max_length=500)
    
    class Meta:
        db_table = "restaurants"

book/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage

import datetime
import time
from .models import Booking , Restaurant

# Create your views here.
def index(request):
    name = request.COOKIES['name']
    bookings = Booking.objects.filter(bookname=name)
    # print(request.COOKIES['name'])
    # print(booking)
    return render(request,'booking/index.html',locals())

def create(request):
    if request.method == "POST":
        #取得表單透過POST傳過來的資料
        restaurantname = request.POST['restaurantname']
        bookname = request.POST['bookname']
        bookperson = request.POST['bookperson']
        booktel = request.POST['booktel']
        bookdate = request.POST['bookdate']
        bookwhen = request.POST['bookwhen'] 
        booktime = time.strftime("%Y-%m-%d %H:%M", time.localtime()) 
        
        
        #todo 把資料寫進資料庫
        Booking.objects.create(restaurantname=restaurantname,bookname=bookname,bookperson=bookperson,booktel=booktel,bookdate=bookdate,bookwhen=bookwhen,booktime=booktime)
        return redirect('/book/')
        
    restaurants = Restaurant.objects.all()
    now = time.strftime("%Y-%m-%d", time.localtime()) 
    return render(request,'booking/create.html',locals())

def update(request, id):
    pass
    if request.method == "POST":
        #取得表單透過POST傳過來的資料
        restaurantname = request.POST['restaurantname']
        bookname = request.POST['bookname']
        bookperson = request.POST['bookperson']
        booktel = request.POST['booktel']
        bookdate = request.POST['bookdate']
        bookwhen = request.POST['bookwhen']     
        Booking.objects.update(restaurantname=restaurantname,bookname=bookname,bookperson=bookperson,booktel=booktel,bookdate=bookdate,bookwhen=bookwhen)
        return redirect('/book/')
#     #步驟一
    books = list(Booking.objects.filter(id=id).values())
    books = books[0]
    print(books)
#     Booking = Book()
#     data = Booking.single(id)
#     restaurants = restaurant()
    restaurants = Restaurant.objects.all()
#     now = time.strftime("%Y-%m-%d", time.localtime()) 
    return render(request,'booking/update.html',locals())
def delete(request, id):
    booking = Booking.objects.get(id=int(id))
    booking.delete()
    return redirect('/book/')

book/templates/booking/create.html
{% extends 'base.html' %}
{% block body %}
<h2 style="text-align: center">{{request.COOKIES.name}}先生，請新增你的定位</h2>
<hr />
<form method="POST" enctype="multipart/form-data"  style="width: 50%;margin:15px auto">
    {% csrf_token %}
    <div class="form-group row">
      <label for="restaurantname" class="col-sm-2 col-form-label col-form-label-lg">餐廳名稱</label>
      <div class="col-sm-10">
        <select class="form-control form-control-lg" name="restaurantname" id="restaurantname">
            <option value="0">請選擇</option>
            {% for restaurant in restaurants%} 
            <option value={{restaurant.rname}}>{{restaurant.rname}}-----{{restaurant.rtype}}</option>
            {% endfor %}
        </select> 
      </div>
    </div>
  <div class="form-group row">
    <label for="bookname" class="col-sm-2 col-form-label col-form-label-lg">訂位大名</label>
    <div class="col-sm-10">
      <input type="text" class="form-control form-control-lg" autocomplete="off" name="bookname" id="bookname" value='{{request.COOKIES.name}}' readonly="readonly" required>
      
    </div>
  </div>
  <div class="form-group row">
    <label for="bookperson" class="col-sm-2 col-form-label col-form-label-lg">訂位人數</label>
    <div class="col-sm-10">
      <input type="number"  max="12" min="2" class="form-control form-control-lg" name="bookperson" id="bookperson" value="2">
    </div>
  </div>
  <div class="form-group row">
    <label for="booktel" class="col-sm-2 col-form-label col-form-label-lg">訂位電話</label>
    <div class="col-sm-10">
      <input type="tel" class="form-control form-control-lg" autocomplete="off" name="booktel" id="booktel" placeholder="請輸入訂位電話" required>
    </div>
  </div>
  <div class="form-group row">
    <label for="bookdate" class="col-sm-2 col-form-label col-form-label-lg">用餐日期</label>
    <div class="col-sm-10">
      <input type="date" min ="{{now}}" max="2020-12-31" class="form-control form-control-lg" name="bookdate" id="bookdate" placeholder="請輸入訂位日期" required>
    </div>
  </div>
  <div class="form-group row">
    <label for="bookwhen" class="col-sm-2 col-form-label col-form-label-lg">用餐日期</label>
    <div class="col-sm-10">
      <input type="time" step='900' class="form-control form-control-lg" name="bookwhen" id="bookwhen" placeholder="請輸入訂位日期" required>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary"><i class="fas fa-plus-square"></i> 我要訂位</button>
      <button type ="reset" class="btn btn-primary"><i class="fas fa-eraser"></i>我要重寫</button>
    </div>
  </div>
</form>
{% endblock %}

book/templates/booking/index.html
{% extends 'base.html' %}
{% block body %}
<h2 style="text-align: center">訂位清單<a href="{% url 'book:create' %}" class="btn btn-primary"><i class="fas fa-plus-square"></i>訂位新增</a></h2>

<table class="table table-bordered" style="margin: 15px auto;text-align: center">
    <thead>
        <tr class="row">
            <th class="col-2"><i style="padding-left:15px" class="fas fa-utensils"></i></th>
            <th class="col-1">訂位大名</th>
            <th class="col-1">訂位餐廳</th>
            <th class="col-1">訂位人數</th>
            <th class="col-1">訂位電話</th>
            <th class="col-1">用餐日期</th>
            <th class="col-1">用餐時間</th>
            <th class="col-2">訂位時間</th>
            <th class="col-1">編輯訂位</th>
            <th class="col-1">刪除訂位</th>
        </tr>
    </thead>
    <tbody>
        {% for booking in bookings %}
        <tr class="row">
            <td class="col-2">請於用餐時間10分鐘前報到</td>
            <td class="col-1">{{booking.bookname}}</td>
            <td class="col-1">{{booking.restaurantname}}</td>
            <td class="col-1">{{booking.bookperson}}</td>
            <td class="col-1">{{booking.booktel}}</td>
            <td class="col-1">{{booking.bookdate}}</td>
            <td class="col-1">{{booking.bookwhen}}</td>
            <td class="col-2">{{booking.booktime}}</td>
            </td>
            <td class="col-1">
                    <a href="{% url 'book:update' booking.id  %}" class="btn btn-secondary"><i class="fas fa-pencil-alt"></i></a>
                    </td>
                    <td class="col-1">
                    <a href="{% url 'book:delete' booking.id  %}" class="btn btn-secondary"><i class="fas fa-trash-alt"></i></a>
                </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block scripts %}

<script>
    $(document).ready(function () {
        $('td').css({ 'background-color': 'lightgreen','font-size':'18px'})
            .mouseover(over)
            .mouseout(out)
        function over() {
            $(this).css({'background-color':'red','font-size':'24px'})
            
        }
        function out() {
            $(this).css({'background-color':'lightgreen','font-size':'18px'});

        }
    })





</script>
{% endblock %} 

book/templates/booking/update.html
{% extends 'base.html' %} {% block body %}
<h2 style="text-align: center">編輯您的訂位</h2>
<hr />
<h1 style="text-align: center">您在{{books.booktime}}訂位</h1>
<form method="POST" enctype="multipart/form-data" style="width: 50%;margin:15px auto">
  {% csrf_token %}
  <div class="form-group row">
    <label for="restaurantname" class="col-sm-2 col-form-label col-form-label-lg">餐廳名稱</label>
    <div class="col-sm-10">
      <select class="form-control form-control-lg" name="restaurantname" id="restaurantname">
          <option value="0">請選擇</option>
          {% for restaurant in restaurants%} 
          {% if books.restaurantname == restaurant.rname %}
          <option selected="selected">{{books.restaurantname}}-----{{restaurant.rtype}}</option>
          {% else %}
          <option>{{restaurant.rname}}-----{{restaurant.rtype}}</option>
          {% endif %}
          {% endfor %}
      </select> 
    </div>
  </div>
  <div class="form-group row">
    <label for="bookname" class="col-sm-2 col-form-label col-form-label-lg">訂位大名</label>
    <div class="col-sm-10">
      <input type="hidden" name="bookid" value="{{books.id}}" />
      <input type="text" autocomplete="off" class="form-control form-control-lg" name="bookname" id="bookname" value="{{books.bookname}}">
    </div>
  </div>
  <div class="form-group row">
    <label for="bookperson" class="col-sm-2 col-form-label col-form-label-lg">訂位人數</label>
    <div class="col-sm-10">
      <input type="number" max="12" min="2" class="form-control form-control-lg" name="bookperson" id="bookperson" value="{{books.bookperson}}">
    </div>
  </div>
  <div class="form-group row">
    <label for="booktel" class="col-sm-2 col-form-label col-form-label-lg">訂位電話</label>
    <div class="col-sm-10">
      <input type="tel" autocomplete="off" class="form-control form-control-lg" name="booktel" id="booktel" value="{{books.booktel}}">
    </div>
  </div>
  <div class="form-group row">
    <label for="bookdate" class="col-sm-2 col-form-label col-form-label-lg">用餐日期</label>
    <div class="col-sm-10">
      <input type="date" min ="{{now}}" max="2020-12-31" class="form-control form-control-lg" name="bookdate" id="bookdate" value="{{books.bookdate}}">
    </div>
  </div>
  <div class="form-group row">
    <label for="bookwhen" class="col-sm-2 col-form-label col-form-label-lg">用餐時間</label>
    <div class="col-sm-10">
      <input type="time" step='900' class="form-control form-control-lg" name="bookwhen" id="bookwhen" placeholder="請輸入訂位日期" value="{{books.bookwhen}}">
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">
        <i class="fas fa-wrench">我要修改</button></i>

    </div>
  </div>
</form>

{% endblock %} {{data.2}}