book/urls.py
from django.urls import path
from . import views

app_name="book"
urlpatterns = [
    #http://localhost:8000/book
    path('',views.index,name="index"),
    path('create/',views.create,name="create"),
    path('update/<int:id>',views.update,name="update"),
    path('delete/<int:id>',views.delete,name="delete")
]

bookingsystem/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('home.urls')),
    path('book/',include('book.urls')),
    path('restaurant/',include('restaurant.urls')),
    path('member/',include('member.urls'))
]

member/urls.py
from django.urls import path
from . import views

app_name = 'member'

urlpatterns = [
    # path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('create/',views.create,name='create')
]

restaurant/urls.py
from django.urls import path
from . import views

app_name="restaurants"
urlpatterns = [
    #http://localhost:8000/product
    path('',views.index,name="index"),
    #http://localhost:8000/product/create
    path('create/',views.create,name="create"),
    #http://localhost:8000/product/update
    path('update/<int:id>',views.update,name="update"),
    #http://localhost:8000/product/delete/1
    path('delete/<int:id>',views.delete,name="delete")
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="zh-tw">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>歡迎來到訂餐廳網站</title>
    <link rel="shortcut icon" href="{% static 'images/index.jpg' %}" />
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    
    
    <title></title>
    <style>
    .backimage{
        background-image: url("{% static 'images/index.jpg' %}");
        background-color: #cccccc;
        height: 800px;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        position: relative;
    }
    s1{
      background-color:'red';
      font-size:24px
    }
    s2{
      background-color: 'lightgreen';
      font-size:18px
    }
    </style>

  </head>
  <body class="backimage">
    {% include 'nav.html' %}

    {% block body%}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
      crossorigin="anonymous"></script>
    {% block scripts%}
    {% endblock %}
    
  </body>
</html>

templates/nav.html
<ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'restaurants:index' %}"><i class="fas fa-utensils"></i>餐廳列表</a>
    </li>
    {% if request.COOKIES.name %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'member:logout' %}"><i class="fas fa-user"></i>登出</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'book:index' %}"><i class="fas fa-book"></i>訂位系統</a>
    </li>
    {%else%}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'member:create' %}"><i class="fas fa-user"></i>申請會員</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'member:login' %}"><i class="fas fa-user"></i>會員登入</a>
    </li>


    
    {%endif%}
  </ul>